# Generated by Django 4.2.5 on 2024-01-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spect',
            fields=[
                ('spect_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('exptime', models.FloatField()),
                ('min_wavelenght', models.FloatField()),
                ('max_wavelenght', models.FloatField()),
                ('file', models.FileField(upload_to='')),
                ('header', models.TextField()),
                ('jd', models.FloatField()),
                ('hjd', models.FloatField()),
                ('sn', models.FloatField()),
                ('instrument', models.CharField(max_length=30)),
                ('outburts', models.BooleanField()),
                ('ob', models.IntegerField()),
                ('state', models.CharField(choices=[('soft', 'Soft'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default='soft', max_length=12)),
                ('flux_calibrated', models.BooleanField()),
                ('spect_resolution', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.source')),
            ],
        ),
    ]
