# Generated by Django 4.2.5 on 2024-01-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('pretty_name', models.CharField(max_length=30)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='spect',
            name='source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='spect',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.object'),
            preserve_default=False,
        ),
    ]
