# Generated by Django 4.2.5 on 2024-01-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_object_remove_spect_source_delete_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spect',
            name='flux_calibrated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spect',
            name='instrument',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spect',
            name='ob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spect',
            name='outburts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spect',
            name='sn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spect',
            name='spect_resolution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
