# Generated by Django 4.2.5 on 2024-01-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_alter_spect_flux_calibrated_alter_spect_instrument_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spect',
            unique_together={('object', 'exptime', 'jd')},
        ),
    ]
