# Generated by Django 4.2.5 on 2024-02-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0007_alter_object_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spect',
            name='slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
